### ISSUE TITLE
Wiki/README confusing

### ISSUE THREAD

**Issue by swordsreversed** [scandiwebcom/Menu-Manager-for-Magento-2-by-Scandiweb#2]
It took a few hours for me to get the menu manager up and running, mainly because i'm new to Mage and I found the instructions confusing. First as in issue #1, the repos you are told to pull are protected bitbucket repos. If you change them to the github equivalents the instructions work.

Secondly fixing the wiki and adding an example would help. The example is in the README but the instructions are in the wiki. Also the example is confusing. I found that ```custom.topnav``` and ```custom.navigation``` didn't work for me, I'm not sure if they are supposed to be place holders? I'm extending from Blank theme so I searched and found 'catalog.topnav' worked for me.

Also, as I didn't really understand the argument syntax I kept changing the name="" section from identifier to my menu identifier, 'skc-menu', eg i was using: 

```
<argument name="skc-menu" xsi:type="string">main_navigation</argument>
```

Dumb I know, but just adding:

```
eg if your Menu Identifier is 'cool-menu':

<move element="catalog.topnav" destination="store.menu" after=""/>
        <referenceContainer name="page.top">
            <block class="Scandiweb\Menumanager\Block\Menu" name="catalog.topnav" template="html/menu.phtml" ttl="3600">
                <arguments>
                    <argument name="main_navigation" xsi:type="string">cool-menu</argument>
                </arguments>
            </block>
        </referenceContainer>
```

to the wiki might help a noob like me from wasting a couple hours. Great project!

**Comment by scandiwebcom** [comment]
Hi, @swordsreversed !
Your comment is much appreciated. We'll definitely look into improving the documentation to make it more convenient for everyone.

Feel free to ping us if you find anything else or there's anything that you would like to clarify.

**Comment by swordsreversed** [comment]
Thanks! I'll do a pull request on the readme and send it in.
