### ISSUE TITLE
Specified invalid parent id (Scandiweb_Core::all)

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [scandiwebcom/Menu-Manager-for-Magento-2-by-Scandiweb#7]
When i install this module then i am getting this error

Specified invalid parent id (Scandiweb_Core::all)

**Comment by scandiwebcom** [comment]
Hi, sumeetmobiwebtech!

It could be that you haven't installed the Core module before the Menu Manager

For installation, run the following:
composer config repositories.module-core git https://github.com/scandiwebcom/Scandiweb-Assets-Core.git
composer require scandiweb/module-core:"dev-master as 0.1.0"

Let us know if this helps.
